# Generated by Django 5.0.6 on 2024-05-14 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/prescription/')),
                ('status', models.CharField(choices=[('DELETED', 'User deleted'), ('ACTIVE', 'Active user'), ('INACTIVE', 'Inactive user')], default='INACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
