# Generated by Django 5.0.6 on 2024-06-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_management', '0003_prescription_active_alter_prescription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INPROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('CANCELED', 'Canceled')], default='INACTIVE', max_length=20),
        ),
    ]
