# Generated by Django 5.0.6 on 2024-06-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_management', '0006_prescription_description_prescription_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_id',
            field=models.CharField(default='PRESC1262626', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
    ]
