# Generated by Django 5.0.6 on 2024-06-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='receiver',
            field=models.IntegerField(default=1),
        ),
    ]
