# Generated by Django 5.0.6 on 2024-06-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_ordermedicine_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INPROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
    ]
