# Generated by Django 5.0.6 on 2024-06-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prescription',
        ),
    ]
