# Generated by Django 5.0.6 on 2024-06-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_remove_order_description_remove_order_prescription'),
        ('prescription_management', '0006_prescription_description_prescription_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ORDER12212122', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescription_management.prescription'),
        ),
    ]
