# Generated by Django 5.0.6 on 2024-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0010_remove_order_total_price_order_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prescription',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
